author = 'Oxalin'
country_code = 'GB'
description = "Portsmouth Direct Line from Farncombe to Rowlands Castle (2021)"
display_name = 'Portsmouth Direct Line (2021)'
doc_files = [ 'Portsmouth_Direct_Line.md' ]
factual = true
img_files = [ 'Portsmouth_Direct_Line_2021.bmp' ]
name = 'Portsmouth Direct Line (2021)'
release_date = '2025-11-04'
rly_file = 'Portsmouth_Direct_Line_2021.rly'
ssn_files = []
ttb_files = [ 'Portsmouth_Direct_Line_2021-05-12.ttb' ]
year = 2021
signal_position - "left"
version = '2.0.0'
